package Exception_Handling;

public class Test_1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		      int[] List = {1, 2, 3};
		      System.out.println(List[4]);
		    } 
		catch (Exception e) 
		{
		      System.out.println("Incorrect Value");
		}
		     
	}
}
